Repository tensorchord/envd-server, pull requests merged in 2022-11, with the labels that each got.

#47 bug: fix certificate problem on k8s pod
  Dockerfile
Labels: approved

#43 feat: clone git repo when info available
  api/types/environment.go
  pkg/consts/consts.go
  pkg/server/environment_create.go
  pkg/util/imageutil/label.go
Labels: approved, lgtm

#48 chore: change label name
  pkg/consts/consts.go
  pkg/server/environment_create.go
Labels: approved

#50 chore: add debug info to env create
  client/image_get.go
  pkg/server/environment_create.go
  pkg/server/image_get.go
Labels: approved

#51 feat: filter label when generateEnvironmentFromPod
  go.mod
  pkg/consts/consts.go
  pkg/server/environment_list.go
  pkg/util/filter.go
Labels: approved

#52 fix: inpsect image size from layer data
  pkg/server/environment_create.go
Labels: approved

#57 bug: Fix release pipeline on arm
  .github/workflows/release.yml
Labels: approved

#59 refact: move environment struct to server
  api/types/environment.go
  pkg/consts/consts.go
  pkg/docs/docs.go
  pkg/server/environment_list.go
Labels: approved

#60 chore: update version in the code and helm
  cmd/envd-server/main.go
  manifests/values.yaml
  pkg/docs/docs.go
Labels: approved

#67 refact: align image lable prefix and pod label prefix
  pkg/consts/consts.go
  pkg/server/environment_create.go
  pkg/server/environment_get.go
  pkg/server/environment_list.go
  pkg/server/environment_remove.go
Labels: approved

#63 feat: add database support
  go.mod
  go.sum
  manifests/templates/deployment.yaml
  manifests/templates/postgres.yaml
  manifests/values.yaml
  pkg/app/server.go
  pkg/query/db.go
  pkg/query/models.go
  pkg/query/query.sql.go
  pkg/server/auth.go
  pkg/server/auth_middleware.go
  pkg/server/containerssh.go
  pkg/server/environment_create.go
  pkg/server/image_get.go
  pkg/server/image_list.go
  pkg/server/server.go
  pkg/util/dao.go
  query/query.sql
  query/schema.sql
  sqlc.yaml
Labels: approved, lgtm

#74 chore: Update default version in chart
  .github/workflows/release.yml
  manifests/values.yaml
Labels: lgtm

#77 chore: Add test cases for environment list
  .github/workflows/CI.yml
  go.mod
  go.sum
  pkg/server/auth_middleware.go
  pkg/server/environment_create.go
  pkg/server/environment_get.go
  pkg/server/environment_list.go
  pkg/server/environment_remove.go
  pkg/server/server.go
  test/environments/list_test.go
  test/environments/suite_test.go
  test/util/environment.go
  test/util/server.go
Labels: lgtm

#82 chore: Refactor image fetch
  pkg/image/image.go
  pkg/server/environment_create.go
Labels: lgtm
