Repository tensorchord/envd-server, pull requests merged in 2022-10, with the labels that each got.

#10 :bug: fix json tag to snake_case
  api/types/environment.go
Labels: approved, lgtm

#9 :hammer: rename kube-config to kubeconfig
  pkg/app/server.go
Labels: lgtm

#11 feat: Support attach from envd CLI
  README.md
  client/options.go
  go.mod
  go.sum
  manifests/deployment.yaml
  pkg/app/server.go
  pkg/server/containerssh.go
  pkg/server/environment.go
  pkg/server/ping.go
  pkg/server/server.go
Labels: approved

#13 feat(env): Support env creation
  .github/workflows/CI.yml
  .golangci.yml
  api/types/environment.go
  client/environment_list.go
  pkg/server/environment_create.go
  pkg/server/environment_list.go
  pkg/server/server.go
Labels: approved

#14 feat: Add API doc
  .github/workflows/CI.yml
  .gitignore
  .swaggo
  Makefile
  api/types/auth.go
  api/types/environment.go
  cmd/envd-server/main.go
  go.mod
  go.sum
  pkg/server/auth.go
  pkg/server/containerssh.go
  pkg/server/environment_create.go
  pkg/server/environment_list.go
  pkg/server/ping.go
  pkg/server/server.go
Labels: approved, lgtm

#15 fix: Enable forwarding in ssh config
  manifests/deployment.yaml
Labels: approved, lgtm

#16 chore: go mod tidy to generate API doc in CI
  .github/workflows/CI.yml
  .gitignore
  .golangci.yml
  pkg/docs/docs.go
Labels: approved, lgtm

#21 feat: Add helm chart
  README.md
  manifests/.helmignore
  manifests/Chart.yaml
  manifests/deployment.yaml
  manifests/secretkeys/backend_pod
  manifests/secretkeys/backend_pod.pub
  manifests/secretkeys/hostkey
  manifests/secretkeys/hostkey.pub
  manifests/templates/NOTES.txt
  manifests/templates/_helpers.tpl
  manifests/templates/configmap.yaml
  manifests/templates/deployment.yaml
  manifests/templates/ingress.yaml
  manifests/templates/role.yaml
  manifests/templates/rolebinding.yaml
  manifests/templates/secret.yaml
  manifests/templates/service.yaml
  manifests/templates/serviceaccount.yaml
  manifests/templates/tests/test-connection.yaml
  manifests/values.yaml
  pkg/server/environment_create.go
Labels: approved

#28 chore: Use middleware to auth
  api/types/auth.go
  api/types/environment.go
  pkg/docs/docs.go
  pkg/server/auth_middleware.go
  pkg/server/environment_list.go
  pkg/server/environment_remove.go
  pkg/server/server.go
Labels: approved, lgtm

#40 chore: update readme toturial
  README.md
  manifests/values.yaml
Labels: approved

#41 feat: rm env will rm pod and service
  Makefile
  cmd/envd-server/main.go
  pkg/server/auth.go
  pkg/server/containerssh.go
  pkg/server/environment_create.go
  pkg/server/environment_get.go
  pkg/server/environment_list.go
  pkg/server/environment_remove.go
  pkg/server/ping.go
Labels: approved

#42 chore: avoid rewrite the status code when auth failed
  pkg/server/auth_middleware.go
  pkg/server/environment_get.go
Labels: approved
